{% set name = "alembic-utils" %}
{% set version = "0.8.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/alembic_utils-{{ version }}.tar.gz
  sha256: 99de5d13194f26536bc0322f0c1660020a305015700d8447ccfc20e7d1494e5b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - alembic >=1.9
    - flupy
    - parse >=1.8.4
    - sqlalchemy >=1.4
    - typing_extensions

test:
  imports:
    - alembic_utils
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/olirice/alembic_utils
  summary: A sqlalchemy/alembic extension for migrating procedures and views
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - abraha2d
